name: Deploy Yew site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Rust project
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: wasm32-unknown-unknown
            override: true
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Generate feeds
        run: cargo run 

      - name: Build Wasm SSR Bundle
        run: wasm-pack build --target web --release

      - name: List all # to know what to exlude in deno.json
        run: ls -lah

      - name: update tailwindcss
        uses: ZoeyVid/tailwindcss-update@main
        with:
          input: static/input.css
          output: static/output.css
          params: "--minify"

      - uses: denoland/setup-deno@v2
        with:
          deno-version: lts
          cache: true

      - name: Minify with esbuild
        run: deno run -A npm:esbuild --minify pkg/my_site.js --outfile=pkg/my_site.mini.js
      
      - name: Gather files for deployment
        run: |
          mkdir build_output
          # Copy only the files the target repo needs to run the site
          cp -r pkg build_output/
          cp -r static build_output/
          ls -la
          ls -la build_output/
          ls -la build_output/pkg/
          ls -la build_output/static/
          rm -f build_output/pkg/.gitignore 
          rm -f .gitignore 
          # If you have an index.html or other assets, copy them too:
          cp main.ts build_output/
          cp deno.json build_output/
          cp robot.txt build_output/
          # Clean up unminified files if you don't want them in the new repo
          rm build_output/pkg/my_site.js

      - name: Push to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build_output'
          destination-github-username: 'abhinandh-s'
          destination-repository-name: 'site'
          user-email: 'abhinandhsuby@proton.me'
          target-branch: 'master' # Or whichever branch you want to push to
          commit-message: 'Deploy built assets from Yew project'

      # - name: Upload to Deno Deploy
        # run: deno deploy --org abhinandh-s --app cma --prod --entrypoint main.ts 
        
         # root: "."
          # Filter which files to exclude in the deployment
          # It supports a single file, multiple files separated by a comma or by a newline
          # Optional.
         # exclude: |
         #   .git 
          # dist
       #    target
          #  dev.tmux
        #    justfile
         #   flake.*
           # *.md
#
